// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

@file:Suppress("NAME_SHADOWING")

package sn.kaolack.fluxsync

// Common helper code.
//
// Ideally this would live in a separate .kt file where it can be unittested etc
// in isolation, and perhaps even published as a re-useable package.
//
// However, it's important that the details of how this helper code works (e.g. the
// way that different builtin types are passed across the FFI) exactly match what's
// expected by the Rust code on the other side of the interface. In practice right
// now that means coming from the exact some version of `uniffi` that was used to
// compile the Rust component. The easiest way to ensure this is to bundle the Kotlin
// helpers directly inline like we're doing here.

import com.sun.jna.Library
import com.sun.jna.IntegerType
import com.sun.jna.Native
import com.sun.jna.Pointer
import com.sun.jna.Structure
import com.sun.jna.Callback
import com.sun.jna.ptr.*
import java.nio.ByteBuffer
import java.nio.ByteOrder
import java.nio.CharBuffer
import java.nio.charset.CodingErrorAction
import java.util.concurrent.atomic.AtomicLong
import java.util.concurrent.ConcurrentHashMap
import java.util.concurrent.atomic.AtomicBoolean

// This is a helper for safely working with byte buffers returned from the Rust code.
// A rust-owned buffer is represented by its capacity, its current length, and a
// pointer to the underlying data.

/**
 * @suppress
 */
@Structure.FieldOrder("capacity", "len", "data")
open class RustBuffer : Structure() {
    // Note: `capacity` and `len` are actually `ULong` values, but JVM only supports signed values.
    // When dealing with these fields, make sure to call `toULong()`.
    @JvmField var capacity: Long = 0
    @JvmField var len: Long = 0
    @JvmField var data: Pointer? = null

    class ByValue: RustBuffer(), Structure.ByValue
    class ByReference: RustBuffer(), Structure.ByReference

   internal fun setValue(other: RustBuffer) {
        capacity = other.capacity
        len = other.len
        data = other.data
    }

    companion object {
        internal fun alloc(size: ULong = 0UL) = uniffiRustCall() { status ->
            // Note: need to convert the size to a `Long` value to make this work with JVM.
            UniffiLib.ffi_fluxsync_mobile_ffi_rustbuffer_alloc(size.toLong(), status)
        }.also {
            if(it.data == null) {
               throw RuntimeException("RustBuffer.alloc() returned null data pointer (size=${size})")
           }
        }

        internal fun create(capacity: ULong, len: ULong, data: Pointer?): RustBuffer.ByValue {
            var buf = RustBuffer.ByValue()
            buf.capacity = capacity.toLong()
            buf.len = len.toLong()
            buf.data = data
            return buf
        }

        internal fun free(buf: RustBuffer.ByValue) = uniffiRustCall() { status ->
            UniffiLib.ffi_fluxsync_mobile_ffi_rustbuffer_free(buf, status)
        }
    }

    @Suppress("TooGenericExceptionThrown")
    fun asByteBuffer() =
        this.data?.getByteBuffer(0, this.len)?.also {
            it.order(ByteOrder.BIG_ENDIAN)
        }
}

// This is a helper for safely passing byte references into the rust code.
// It's not actually used at the moment, because there aren't many things that you
// can take a direct pointer to in the JVM, and if we're going to copy something
// then we might as well copy it into a `RustBuffer`. But it's here for API
// completeness.

@Structure.FieldOrder("len", "data")
internal open class ForeignBytes : Structure() {
    @JvmField var len: Int = 0
    @JvmField var data: Pointer? = null

    class ByValue : ForeignBytes(), Structure.ByValue
}
/**
 * The FfiConverter interface handles converter types to and from the FFI
 *
 * All implementing objects should be public to support external types.  When a
 * type is external we need to import it's FfiConverter.
 *
 * @suppress
 */
public interface FfiConverter<KotlinType, FfiType> {
    // Convert an FFI type to a Kotlin type
    fun lift(value: FfiType): KotlinType

    // Convert an Kotlin type to an FFI type
    fun lower(value: KotlinType): FfiType

    // Read a Kotlin type from a `ByteBuffer`
    fun read(buf: ByteBuffer): KotlinType

    // Calculate bytes to allocate when creating a `RustBuffer`
    //
    // This must return at least as many bytes as the write() function will
    // write. It can return more bytes than needed, for example when writing
    // Strings we can't know the exact bytes needed until we the UTF-8
    // encoding, so we pessimistically allocate the largest size possible (3
    // bytes per codepoint).  Allocating extra bytes is not really a big deal
    // because the `RustBuffer` is short-lived.
    fun allocationSize(value: KotlinType): ULong

    // Write a Kotlin type to a `ByteBuffer`
    fun write(value: KotlinType, buf: ByteBuffer)

    // Lower a value into a `RustBuffer`
    //
    // This method lowers a value into a `RustBuffer` rather than the normal
    // FfiType.  It's used by the callback interface code.  Callback interface
    // returns are always serialized into a `RustBuffer` regardless of their
    // normal FFI type.
    fun lowerIntoRustBuffer(value: KotlinType): RustBuffer.ByValue {
        val rbuf = RustBuffer.alloc(allocationSize(value))
        try {
            val bbuf = rbuf.data!!.getByteBuffer(0, rbuf.capacity).also {
                it.order(ByteOrder.BIG_ENDIAN)
            }
            write(value, bbuf)
            rbuf.writeField("len", bbuf.position().toLong())
            return rbuf
        } catch (e: Throwable) {
            RustBuffer.free(rbuf)
            throw e
        }
    }

    // Lift a value from a `RustBuffer`.
    //
    // This here mostly because of the symmetry with `lowerIntoRustBuffer()`.
    // It's currently only used by the `FfiConverterRustBuffer` class below.
    fun liftFromRustBuffer(rbuf: RustBuffer.ByValue): KotlinType {
        val byteBuf = rbuf.asByteBuffer()!!
        try {
           val item = read(byteBuf)
           if (byteBuf.hasRemaining()) {
               throw RuntimeException("junk remaining in buffer after lifting, something is very wrong!!")
           }
           return item
        } finally {
            RustBuffer.free(rbuf)
        }
    }
}

/**
 * FfiConverter that uses `RustBuffer` as the FfiType
 *
 * @suppress
 */
public interface FfiConverterRustBuffer<KotlinType>: FfiConverter<KotlinType, RustBuffer.ByValue> {
    override fun lift(value: RustBuffer.ByValue) = liftFromRustBuffer(value)
    override fun lower(value: KotlinType) = lowerIntoRustBuffer(value)
}
// A handful of classes and functions to support the generated data structures.
// This would be a good candidate for isolating in its own ffi-support lib.

internal const val UNIFFI_CALL_SUCCESS = 0.toByte()
internal const val UNIFFI_CALL_ERROR = 1.toByte()
internal const val UNIFFI_CALL_UNEXPECTED_ERROR = 2.toByte()

@Structure.FieldOrder("code", "error_buf")
internal open class UniffiRustCallStatus : Structure() {
    @JvmField var code: Byte = 0
    @JvmField var error_buf: RustBuffer.ByValue = RustBuffer.ByValue()

    class ByValue: UniffiRustCallStatus(), Structure.ByValue

    fun isSuccess(): Boolean {
        return code == UNIFFI_CALL_SUCCESS
    }

    fun isError(): Boolean {
        return code == UNIFFI_CALL_ERROR
    }

    fun isPanic(): Boolean {
        return code == UNIFFI_CALL_UNEXPECTED_ERROR
    }

    companion object {
        fun create(code: Byte, errorBuf: RustBuffer.ByValue): UniffiRustCallStatus.ByValue {
            val callStatus = UniffiRustCallStatus.ByValue()
            callStatus.code = code
            callStatus.error_buf = errorBuf
            return callStatus
        }
    }
}

class InternalException(message: String) : kotlin.Exception(message)

/**
 * Each top-level error class has a companion object that can lift the error from the call status's rust buffer
 *
 * @suppress
 */
interface UniffiRustCallStatusErrorHandler<E> {
    fun lift(error_buf: RustBuffer.ByValue): E;
}

// Helpers for calling Rust
// In practice we usually need to be synchronized to call this safely, so it doesn't
// synchronize itself

// Call a rust function that returns a Result<>.  Pass in the Error class companion that corresponds to the Err
private inline fun <U, E: kotlin.Exception> uniffiRustCallWithError(errorHandler: UniffiRustCallStatusErrorHandler<E>, callback: (UniffiRustCallStatus) -> U): U {
    var status = UniffiRustCallStatus()
    val return_value = callback(status)
    uniffiCheckCallStatus(errorHandler, status)
    return return_value
}

// Check UniffiRustCallStatus and throw an error if the call wasn't successful
private fun<E: kotlin.Exception> uniffiCheckCallStatus(errorHandler: UniffiRustCallStatusErrorHandler<E>, status: UniffiRustCallStatus) {
    if (status.isSuccess()) {
        return
    } else if (status.isError()) {
        throw errorHandler.lift(status.error_buf)
    } else if (status.isPanic()) {
        // when the rust code sees a panic, it tries to construct a rustbuffer
        // with the message.  but if that code panics, then it just sends back
        // an empty buffer.
        if (status.error_buf.len > 0) {
            throw InternalException(FfiConverterString.lift(status.error_buf))
        } else {
            throw InternalException("Rust panic")
        }
    } else {
        throw InternalException("Unknown rust call status: $status.code")
    }
}

/**
 * UniffiRustCallStatusErrorHandler implementation for times when we don't expect a CALL_ERROR
 *
 * @suppress
 */
object UniffiNullRustCallStatusErrorHandler: UniffiRustCallStatusErrorHandler<InternalException> {
    override fun lift(error_buf: RustBuffer.ByValue): InternalException {
        RustBuffer.free(error_buf)
        return InternalException("Unexpected CALL_ERROR")
    }
}

// Call a rust function that returns a plain value
private inline fun <U> uniffiRustCall(callback: (UniffiRustCallStatus) -> U): U {
    return uniffiRustCallWithError(UniffiNullRustCallStatusErrorHandler, callback)
}

internal inline fun<T> uniffiTraitInterfaceCall(
    callStatus: UniffiRustCallStatus,
    makeCall: () -> T,
    writeReturn: (T) -> Unit,
) {
    try {
        writeReturn(makeCall())
    } catch(e: kotlin.Exception) {
        val err = try { e.stackTraceToString() } catch(_: Throwable) { "" }
        callStatus.code = UNIFFI_CALL_UNEXPECTED_ERROR
        callStatus.error_buf = FfiConverterString.lower(err)
    }
}

internal inline fun<T, reified E: Throwable> uniffiTraitInterfaceCallWithError(
    callStatus: UniffiRustCallStatus,
    makeCall: () -> T,
    writeReturn: (T) -> Unit,
    lowerError: (E) -> RustBuffer.ByValue
) {
    try {
        writeReturn(makeCall())
    } catch(e: kotlin.Exception) {
        if (e is E) {
            callStatus.code = UNIFFI_CALL_ERROR
            callStatus.error_buf = lowerError(e)
        } else {
            val err = try { e.stackTraceToString() } catch(_: Throwable) { "" }
            callStatus.code = UNIFFI_CALL_UNEXPECTED_ERROR
            callStatus.error_buf = FfiConverterString.lower(err)
        }
    }
}
// Initial value and increment amount for handles. 
// These ensure that Kotlin-generated handles always have the lowest bit set
private const val UNIFFI_HANDLEMAP_INITIAL = 1.toLong()
private const val UNIFFI_HANDLEMAP_DELTA = 2.toLong()

// Map handles to objects
//
// This is used pass an opaque 64-bit handle representing a foreign object to the Rust code.
internal class UniffiHandleMap<T: Any> {
    private val map = ConcurrentHashMap<Long, T>()
    // Start 
    private val counter = java.util.concurrent.atomic.AtomicLong(UNIFFI_HANDLEMAP_INITIAL)

    val size: Int
        get() = map.size

    // Insert a new object into the handle map and get a handle for it
    fun insert(obj: T): Long {
        val handle = counter.getAndAdd(UNIFFI_HANDLEMAP_DELTA)
        map.put(handle, obj)
        return handle
    }

    // Clone a handle, creating a new one
    fun clone(handle: Long): Long {
        val obj = map.get(handle) ?: throw InternalException("UniffiHandleMap.clone: Invalid handle")
        return insert(obj)
    }

    // Get an object from the handle map
    fun get(handle: Long): T {
        return map.get(handle) ?: throw InternalException("UniffiHandleMap.get: Invalid handle")
    }

    // Remove an entry from the handlemap and get the Kotlin object back
    fun remove(handle: Long): T {
        return map.remove(handle) ?: throw InternalException("UniffiHandleMap: Invalid handle")
    }
}

// Contains loading, initialization code,
// and the FFI Function declarations in a com.sun.jna.Library.
@Synchronized
private fun findLibraryName(componentName: String): String {
    val libOverride = System.getProperty("uniffi.component.$componentName.libraryOverride")
    if (libOverride != null) {
        return libOverride
    }
    return "fluxsync_mobile_ffi"
}

// Define FFI callback types
internal interface UniffiRustFutureContinuationCallback : com.sun.jna.Callback {
    fun callback(`data`: Long,`pollResult`: Byte,)
}
internal interface UniffiForeignFutureDroppedCallback : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
}
internal interface UniffiCallbackInterfaceFree : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
}
internal interface UniffiCallbackInterfaceClone : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
    : Long
}
@Structure.FieldOrder("handle", "free")
internal open class UniffiForeignFutureDroppedCallbackStruct(
    @JvmField internal var `handle`: Long = 0.toLong(),
    @JvmField internal var `free`: UniffiForeignFutureDroppedCallback? = null,
) : Structure() {
    class UniffiByValue(
        `handle`: Long = 0.toLong(),
        `free`: UniffiForeignFutureDroppedCallback? = null,
    ): UniffiForeignFutureDroppedCallbackStruct(`handle`,`free`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureDroppedCallbackStruct) {
        `handle` = other.`handle`
        `free` = other.`free`
    }

}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultU8(
    @JvmField internal var `returnValue`: Byte = 0.toByte(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Byte = 0.toByte(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultU8(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultU8) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU8 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultU8.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultI8(
    @JvmField internal var `returnValue`: Byte = 0.toByte(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Byte = 0.toByte(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultI8(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultI8) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI8 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultI8.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultU16(
    @JvmField internal var `returnValue`: Short = 0.toShort(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Short = 0.toShort(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultU16(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultU16) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU16 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultU16.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultI16(
    @JvmField internal var `returnValue`: Short = 0.toShort(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Short = 0.toShort(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultI16(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultI16) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI16 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultI16.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultU32(
    @JvmField internal var `returnValue`: Int = 0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Int = 0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultU32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultU32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultU32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultI32(
    @JvmField internal var `returnValue`: Int = 0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Int = 0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultI32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultI32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultI32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultU64(
    @JvmField internal var `returnValue`: Long = 0.toLong(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Long = 0.toLong(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultU64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultU64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultU64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultI64(
    @JvmField internal var `returnValue`: Long = 0.toLong(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Long = 0.toLong(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultI64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultI64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultI64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultF32(
    @JvmField internal var `returnValue`: Float = 0.0f,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Float = 0.0f,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultF32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultF32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteF32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultF32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultF64(
    @JvmField internal var `returnValue`: Double = 0.0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Double = 0.0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultF64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultF64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteF64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultF64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultRustBuffer(
    @JvmField internal var `returnValue`: RustBuffer.ByValue = RustBuffer.ByValue(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: RustBuffer.ByValue = RustBuffer.ByValue(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultRustBuffer(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultRustBuffer) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteRustBuffer : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultRustBuffer.UniffiByValue,)
}
@Structure.FieldOrder("callStatus")
internal open class UniffiForeignFutureResultVoid(
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultVoid(`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultVoid) {
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteVoid : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultVoid.UniffiByValue,)
}

// A JNA Library to expose the extern-C FFI definitions.
// This is an implementation detail which will be called internally by the public API.

// For large crates we prevent `MethodTooLargeException` (see #2340)
// N.B. the name of the extension is very misleading, since it is
// rather `InterfaceTooLargeException`, caused by too many methods
// in the interface for large crates.
//
// By splitting the otherwise huge interface into two parts
// * UniffiLib (this)
// * IntegrityCheckingUniffiLib
// And all checksum methods are put into `IntegrityCheckingUniffiLib`
// we allow for ~2x as many methods in the UniffiLib interface.
//
// Note: above all written when we used JNA's `loadIndirect` etc.
// We now use JNA's "direct mapping" - unclear if same considerations apply exactly.
internal object IntegrityCheckingUniffiLib {
    init {
        Native.register(IntegrityCheckingUniffiLib::class.java, findLibraryName(componentName = "fluxsync_mobile_ffi"))
        uniffiCheckContractApiVersion(this)
        uniffiCheckApiChecksums(this)
    }
    external fun uniffi_fluxsync_mobile_ffi_checksum_method_fluxsynchandle_fetch_item(
    ): Short
    external fun uniffi_fluxsync_mobile_ffi_checksum_method_fluxsynchandle_log_cursor(
    ): Short
    external fun uniffi_fluxsync_mobile_ffi_checksum_method_fluxsynchandle_pair_accept(
    ): Short
    external fun uniffi_fluxsync_mobile_ffi_checksum_method_fluxsynchandle_pair_confirm(
    ): Short
    external fun uniffi_fluxsync_mobile_ffi_checksum_method_fluxsynchandle_pair_from_uri(
    ): Short
    external fun uniffi_fluxsync_mobile_ffi_checksum_method_fluxsynchandle_pair_pending(
    ): Short
    external fun uniffi_fluxsync_mobile_ffi_checksum_method_fluxsynchandle_pair_show(
    ): Short
    external fun uniffi_fluxsync_mobile_ffi_checksum_method_fluxsynchandle_poll_logs(
    ): Short
    external fun uniffi_fluxsync_mobile_ffi_checksum_method_fluxsynchandle_poll_state(
    ): Short
    external fun uniffi_fluxsync_mobile_ffi_checksum_method_fluxsynchandle_push_item(
    ): Short
    external fun uniffi_fluxsync_mobile_ffi_checksum_method_fluxsynchandle_push_text(
    ): Short
    external fun uniffi_fluxsync_mobile_ffi_checksum_method_fluxsynchandle_resolve_pending(
    ): Short
    external fun uniffi_fluxsync_mobile_ffi_checksum_method_fluxsynchandle_revoke(
    ): Short
    external fun uniffi_fluxsync_mobile_ffi_checksum_method_fluxsynchandle_set_battery_threshold(
    ): Short
    external fun uniffi_fluxsync_mobile_ffi_checksum_method_fluxsynchandle_set_charge_override(
    ): Short
    external fun uniffi_fluxsync_mobile_ffi_checksum_method_fluxsynchandle_set_favorite(
    ): Short
    external fun uniffi_fluxsync_mobile_ffi_checksum_method_fluxsynchandle_set_firewall(
    ): Short
    external fun uniffi_fluxsync_mobile_ffi_checksum_method_fluxsynchandle_set_self_battery(
    ): Short
    external fun uniffi_fluxsync_mobile_ffi_checksum_method_fluxsynchandle_stop(
    ): Short
    external fun uniffi_fluxsync_mobile_ffi_checksum_method_fluxsynchandle_toggle(
    ): Short
    external fun uniffi_fluxsync_mobile_ffi_checksum_method_fluxsynchandle_unpair(
    ): Short
    external fun uniffi_fluxsync_mobile_ffi_checksum_constructor_fluxsynchandle_start(
    ): Short
    external fun ffi_fluxsync_mobile_ffi_uniffi_contract_version(
    ): Int

        
}

internal object UniffiLib {
    
    // The Cleaner for the whole library
    internal val CLEANER: UniffiCleaner by lazy {
        UniffiCleaner.create()
    }
    

    init {
        Native.register(UniffiLib::class.java, findLibraryName(componentName = "fluxsync_mobile_ffi"))
        
    }
    external fun uniffi_fluxsync_mobile_ffi_fn_clone_fluxsynchandle(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Long
    external fun uniffi_fluxsync_mobile_ffi_fn_free_fluxsynchandle(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    external fun uniffi_fluxsync_mobile_ffi_fn_constructor_fluxsynchandle_start(`peerName`: RustBuffer.ByValue,`ipcPath`: RustBuffer.ByValue,`udpPort`: Short,`identity`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Long
    external fun uniffi_fluxsync_mobile_ffi_fn_method_fluxsynchandle_fetch_item(`ptr`: Long,`hash`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_fluxsync_mobile_ffi_fn_method_fluxsynchandle_log_cursor(`ptr`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Long
    external fun uniffi_fluxsync_mobile_ffi_fn_method_fluxsynchandle_pair_accept(`ptr`: Long,`pubkeyB32`: RustBuffer.ByValue,`name`: RustBuffer.ByValue,`addr`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    external fun uniffi_fluxsync_mobile_ffi_fn_method_fluxsynchandle_pair_confirm(`ptr`: Long,`peerId`: RustBuffer.ByValue,`accept`: Byte,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    external fun uniffi_fluxsync_mobile_ffi_fn_method_fluxsynchandle_pair_from_uri(`ptr`: Long,`uri`: RustBuffer.ByValue,`name`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    external fun uniffi_fluxsync_mobile_ffi_fn_method_fluxsynchandle_pair_pending(`ptr`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_fluxsync_mobile_ffi_fn_method_fluxsynchandle_pair_show(`ptr`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_fluxsync_mobile_ffi_fn_method_fluxsynchandle_poll_logs(`ptr`: Long,`since`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_fluxsync_mobile_ffi_fn_method_fluxsynchandle_poll_state(`ptr`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_fluxsync_mobile_ffi_fn_method_fluxsynchandle_push_item(`ptr`: Long,`kind`: RustBuffer.ByValue,`bytes`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    external fun uniffi_fluxsync_mobile_ffi_fn_method_fluxsynchandle_push_text(`ptr`: Long,`text`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    external fun uniffi_fluxsync_mobile_ffi_fn_method_fluxsynchandle_resolve_pending(`ptr`: Long,`hash`: RustBuffer.ByValue,`allow`: Byte,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    external fun uniffi_fluxsync_mobile_ffi_fn_method_fluxsynchandle_revoke(`ptr`: Long,`peerId`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    external fun uniffi_fluxsync_mobile_ffi_fn_method_fluxsynchandle_set_battery_threshold(`ptr`: Long,`value`: Byte,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    external fun uniffi_fluxsync_mobile_ffi_fn_method_fluxsynchandle_set_charge_override(`ptr`: Long,`value`: Byte,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    external fun uniffi_fluxsync_mobile_ffi_fn_method_fluxsynchandle_set_favorite(`ptr`: Long,`hash`: RustBuffer.ByValue,`favorite`: Byte,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    external fun uniffi_fluxsync_mobile_ffi_fn_method_fluxsynchandle_set_firewall(`ptr`: Long,`policyJson`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    external fun uniffi_fluxsync_mobile_ffi_fn_method_fluxsynchandle_set_self_battery(`ptr`: Long,`level`: Byte,`charging`: Byte,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    external fun uniffi_fluxsync_mobile_ffi_fn_method_fluxsynchandle_stop(`ptr`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    external fun uniffi_fluxsync_mobile_ffi_fn_method_fluxsynchandle_toggle(`ptr`: Long,`on`: Byte,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    external fun uniffi_fluxsync_mobile_ffi_fn_method_fluxsynchandle_unpair(`ptr`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    external fun ffi_fluxsync_mobile_ffi_rustbuffer_alloc(`size`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun ffi_fluxsync_mobile_ffi_rustbuffer_from_bytes(`bytes`: ForeignBytes.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun ffi_fluxsync_mobile_ffi_rustbuffer_free(`buf`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    external fun ffi_fluxsync_mobile_ffi_rustbuffer_reserve(`buf`: RustBuffer.ByValue,`additional`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun ffi_fluxsync_mobile_ffi_rust_future_poll_u8(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_fluxsync_mobile_ffi_rust_future_cancel_u8(`handle`: Long,
    ): Unit
    external fun ffi_fluxsync_mobile_ffi_rust_future_free_u8(`handle`: Long,
    ): Unit
    external fun ffi_fluxsync_mobile_ffi_rust_future_complete_u8(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Byte
    external fun ffi_fluxsync_mobile_ffi_rust_future_poll_i8(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_fluxsync_mobile_ffi_rust_future_cancel_i8(`handle`: Long,
    ): Unit
    external fun ffi_fluxsync_mobile_ffi_rust_future_free_i8(`handle`: Long,
    ): Unit
    external fun ffi_fluxsync_mobile_ffi_rust_future_complete_i8(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Byte
    external fun ffi_fluxsync_mobile_ffi_rust_future_poll_u16(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_fluxsync_mobile_ffi_rust_future_cancel_u16(`handle`: Long,
    ): Unit
    external fun ffi_fluxsync_mobile_ffi_rust_future_free_u16(`handle`: Long,
    ): Unit
    external fun ffi_fluxsync_mobile_ffi_rust_future_complete_u16(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Short
    external fun ffi_fluxsync_mobile_ffi_rust_future_poll_i16(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_fluxsync_mobile_ffi_rust_future_cancel_i16(`handle`: Long,
    ): Unit
    external fun ffi_fluxsync_mobile_ffi_rust_future_free_i16(`handle`: Long,
    ): Unit
    external fun ffi_fluxsync_mobile_ffi_rust_future_complete_i16(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Short
    external fun ffi_fluxsync_mobile_ffi_rust_future_poll_u32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_fluxsync_mobile_ffi_rust_future_cancel_u32(`handle`: Long,
    ): Unit
    external fun ffi_fluxsync_mobile_ffi_rust_future_free_u32(`handle`: Long,
    ): Unit
    external fun ffi_fluxsync_mobile_ffi_rust_future_complete_u32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Int
    external fun ffi_fluxsync_mobile_ffi_rust_future_poll_i32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_fluxsync_mobile_ffi_rust_future_cancel_i32(`handle`: Long,
    ): Unit
    external fun ffi_fluxsync_mobile_ffi_rust_future_free_i32(`handle`: Long,
    ): Unit
    external fun ffi_fluxsync_mobile_ffi_rust_future_complete_i32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Int
    external fun ffi_fluxsync_mobile_ffi_rust_future_poll_u64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_fluxsync_mobile_ffi_rust_future_cancel_u64(`handle`: Long,
    ): Unit
    external fun ffi_fluxsync_mobile_ffi_rust_future_free_u64(`handle`: Long,
    ): Unit
    external fun ffi_fluxsync_mobile_ffi_rust_future_complete_u64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Long
    external fun ffi_fluxsync_mobile_ffi_rust_future_poll_i64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_fluxsync_mobile_ffi_rust_future_cancel_i64(`handle`: Long,
    ): Unit
    external fun ffi_fluxsync_mobile_ffi_rust_future_free_i64(`handle`: Long,
    ): Unit
    external fun ffi_fluxsync_mobile_ffi_rust_future_complete_i64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Long
    external fun ffi_fluxsync_mobile_ffi_rust_future_poll_f32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_fluxsync_mobile_ffi_rust_future_cancel_f32(`handle`: Long,
    ): Unit
    external fun ffi_fluxsync_mobile_ffi_rust_future_free_f32(`handle`: Long,
    ): Unit
    external fun ffi_fluxsync_mobile_ffi_rust_future_complete_f32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Float
    external fun ffi_fluxsync_mobile_ffi_rust_future_poll_f64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_fluxsync_mobile_ffi_rust_future_cancel_f64(`handle`: Long,
    ): Unit
    external fun ffi_fluxsync_mobile_ffi_rust_future_free_f64(`handle`: Long,
    ): Unit
    external fun ffi_fluxsync_mobile_ffi_rust_future_complete_f64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Double
    external fun ffi_fluxsync_mobile_ffi_rust_future_poll_rust_buffer(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_fluxsync_mobile_ffi_rust_future_cancel_rust_buffer(`handle`: Long,
    ): Unit
    external fun ffi_fluxsync_mobile_ffi_rust_future_free_rust_buffer(`handle`: Long,
    ): Unit
    external fun ffi_fluxsync_mobile_ffi_rust_future_complete_rust_buffer(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun ffi_fluxsync_mobile_ffi_rust_future_poll_void(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_fluxsync_mobile_ffi_rust_future_cancel_void(`handle`: Long,
    ): Unit
    external fun ffi_fluxsync_mobile_ffi_rust_future_free_void(`handle`: Long,
    ): Unit
    external fun ffi_fluxsync_mobile_ffi_rust_future_complete_void(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit

        
}

private fun uniffiCheckContractApiVersion(lib: IntegrityCheckingUniffiLib) {
    // Get the bindings contract version from our ComponentInterface
    val bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    val scaffolding_contract_version = lib.ffi_fluxsync_mobile_ffi_uniffi_contract_version()
    if (bindings_contract_version != scaffolding_contract_version) {
        throw RuntimeException("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    }
}
@Suppress("UNUSED_PARAMETER")
private fun uniffiCheckApiChecksums(lib: IntegrityCheckingUniffiLib) {
    if (lib.uniffi_fluxsync_mobile_ffi_checksum_method_fluxsynchandle_fetch_item() != 46069.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_fluxsync_mobile_ffi_checksum_method_fluxsynchandle_log_cursor() != 49238.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_fluxsync_mobile_ffi_checksum_method_fluxsynchandle_pair_accept() != 27254.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_fluxsync_mobile_ffi_checksum_method_fluxsynchandle_pair_confirm() != 53681.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_fluxsync_mobile_ffi_checksum_method_fluxsynchandle_pair_from_uri() != 26161.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_fluxsync_mobile_ffi_checksum_method_fluxsynchandle_pair_pending() != 12529.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_fluxsync_mobile_ffi_checksum_method_fluxsynchandle_pair_show() != 36878.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_fluxsync_mobile_ffi_checksum_method_fluxsynchandle_poll_logs() != 25054.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_fluxsync_mobile_ffi_checksum_method_fluxsynchandle_poll_state() != 63397.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_fluxsync_mobile_ffi_checksum_method_fluxsynchandle_push_item() != 38274.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_fluxsync_mobile_ffi_checksum_method_fluxsynchandle_push_text() != 51988.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_fluxsync_mobile_ffi_checksum_method_fluxsynchandle_resolve_pending() != 59432.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_fluxsync_mobile_ffi_checksum_method_fluxsynchandle_revoke() != 532.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_fluxsync_mobile_ffi_checksum_method_fluxsynchandle_set_battery_threshold() != 65243.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_fluxsync_mobile_ffi_checksum_method_fluxsynchandle_set_charge_override() != 22905.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_fluxsync_mobile_ffi_checksum_method_fluxsynchandle_set_favorite() != 58674.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_fluxsync_mobile_ffi_checksum_method_fluxsynchandle_set_firewall() != 12791.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_fluxsync_mobile_ffi_checksum_method_fluxsynchandle_set_self_battery() != 25465.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_fluxsync_mobile_ffi_checksum_method_fluxsynchandle_stop() != 13164.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_fluxsync_mobile_ffi_checksum_method_fluxsynchandle_toggle() != 10489.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_fluxsync_mobile_ffi_checksum_method_fluxsynchandle_unpair() != 17136.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_fluxsync_mobile_ffi_checksum_constructor_fluxsynchandle_start() != 30614.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

/**
 * @suppress
 */
public fun uniffiEnsureInitialized() {
    IntegrityCheckingUniffiLib
    // UniffiLib() initialized as objects are used, but we still need to explicitly
    // reference it so initialization across crates works as expected.
    UniffiLib
}

// Async support

// Public interface members begin here.


// Interface implemented by anything that can contain an object reference.
//
// Such types expose a `destroy()` method that must be called to cleanly
// dispose of the contained objects. Failure to call this method may result
// in memory leaks.
//
// The easiest way to ensure this method is called is to use the `.use`
// helper method to execute a block and destroy the object at the end.
interface Disposable {
    fun destroy()
    companion object {
        fun destroy(vararg args: Any?) {
            for (arg in args) {
                when (arg) {
                    is Disposable -> arg.destroy()
                    is ArrayList<*> -> {
                        for (idx in arg.indices) {
                            val element = arg[idx]
                            if (element is Disposable) {
                                element.destroy()
                            }
                        }
                    }
                    is Map<*, *> -> {
                        for (element in arg.values) {
                            if (element is Disposable) {
                                element.destroy()
                            }
                        }
                    }
                    is Iterable<*> -> {
                        for (element in arg) {
                            if (element is Disposable) {
                                element.destroy()
                            }
                        }
                    }
                }
            }
        }
    }
}

/**
 * @suppress
 */
inline fun <T : Disposable?, R> T.use(block: (T) -> R) =
    try {
        block(this)
    } finally {
        try {
            // N.B. our implementation is on the nullable type `Disposable?`.
            this?.destroy()
        } catch (e: Throwable) {
            // swallow
        }
    }

/** 
 * Placeholder object used to signal that we're constructing an interface with a FFI handle.
 *
 * This is the first argument for interface constructors that input a raw handle. It exists is that
 * so we can avoid signature conflicts when an interface has a regular constructor than inputs a
 * Long.
 *
 * @suppress
 * */
object UniffiWithHandle

/** 
 * Used to instantiate an interface without an actual pointer, for fakes in tests, mostly.
 *
 * @suppress
 * */
object NoHandle
/**
 * The cleaner interface for Object finalization code to run.
 * This is the entry point to any implementation that we're using.
 *
 * The cleaner registers objects and returns cleanables, so now we are
 * defining a `UniffiCleaner` with a `UniffiClenaer.Cleanable` to abstract the
 * different implmentations available at compile time.
 *
 * @suppress
 */
interface UniffiCleaner {
    interface Cleanable {
        fun clean()
    }

    fun register(value: Any, cleanUpTask: Runnable): UniffiCleaner.Cleanable

    companion object
}

// The fallback Jna cleaner, which is available for both Android, and the JVM.
private class UniffiJnaCleaner : UniffiCleaner {
    private val cleaner = com.sun.jna.internal.Cleaner.getCleaner()

    override fun register(value: Any, cleanUpTask: Runnable): UniffiCleaner.Cleanable =
        UniffiJnaCleanable(cleaner.register(value, cleanUpTask))
}

private class UniffiJnaCleanable(
    private val cleanable: com.sun.jna.internal.Cleaner.Cleanable,
) : UniffiCleaner.Cleanable {
    override fun clean() = cleanable.clean()
}


// We decide at uniffi binding generation time whether we were
// using Android or not.
// There are further runtime checks to chose the correct implementation
// of the cleaner.
private fun UniffiCleaner.Companion.create(): UniffiCleaner =
    try {
        // For safety's sake: if the library hasn't been run in android_cleaner = true
        // mode, but is being run on Android, then we still need to think about
        // Android API versions.
        // So we check if java.lang.ref.Cleaner is there, and use that…
        java.lang.Class.forName("java.lang.ref.Cleaner")
        JavaLangRefCleaner()
    } catch (e: ClassNotFoundException) {
        // … otherwise, fallback to the JNA cleaner.
        UniffiJnaCleaner()
    }

private class JavaLangRefCleaner : UniffiCleaner {
    val cleaner = java.lang.ref.Cleaner.create()

    override fun register(value: Any, cleanUpTask: Runnable): UniffiCleaner.Cleanable =
        JavaLangRefCleanable(cleaner.register(value, cleanUpTask))
}

private class JavaLangRefCleanable(
    val cleanable: java.lang.ref.Cleaner.Cleanable
) : UniffiCleaner.Cleanable {
    override fun clean() = cleanable.clean()
}

/**
 * @suppress
 */
public object FfiConverterUByte: FfiConverter<UByte, Byte> {
    override fun lift(value: Byte): UByte {
        return value.toUByte()
    }

    override fun read(buf: ByteBuffer): UByte {
        return lift(buf.get())
    }

    override fun lower(value: UByte): Byte {
        return value.toByte()
    }

    override fun allocationSize(value: UByte) = 1UL

    override fun write(value: UByte, buf: ByteBuffer) {
        buf.put(value.toByte())
    }
}

/**
 * @suppress
 */
public object FfiConverterUShort: FfiConverter<UShort, Short> {
    override fun lift(value: Short): UShort {
        return value.toUShort()
    }

    override fun read(buf: ByteBuffer): UShort {
        return lift(buf.getShort())
    }

    override fun lower(value: UShort): Short {
        return value.toShort()
    }

    override fun allocationSize(value: UShort) = 2UL

    override fun write(value: UShort, buf: ByteBuffer) {
        buf.putShort(value.toShort())
    }
}

/**
 * @suppress
 */
public object FfiConverterULong: FfiConverter<ULong, Long> {
    override fun lift(value: Long): ULong {
        return value.toULong()
    }

    override fun read(buf: ByteBuffer): ULong {
        return lift(buf.getLong())
    }

    override fun lower(value: ULong): Long {
        return value.toLong()
    }

    override fun allocationSize(value: ULong) = 8UL

    override fun write(value: ULong, buf: ByteBuffer) {
        buf.putLong(value.toLong())
    }
}

/**
 * @suppress
 */
public object FfiConverterBoolean: FfiConverter<Boolean, Byte> {
    override fun lift(value: Byte): Boolean {
        return value.toInt() != 0
    }

    override fun read(buf: ByteBuffer): Boolean {
        return lift(buf.get())
    }

    override fun lower(value: Boolean): Byte {
        return if (value) 1.toByte() else 0.toByte()
    }

    override fun allocationSize(value: Boolean) = 1UL

    override fun write(value: Boolean, buf: ByteBuffer) {
        buf.put(lower(value))
    }
}

/**
 * @suppress
 */
public object FfiConverterString: FfiConverter<String, RustBuffer.ByValue> {
    // Note: we don't inherit from FfiConverterRustBuffer, because we use a
    // special encoding when lowering/lifting.  We can use `RustBuffer.len` to
    // store our length and avoid writing it out to the buffer.
    override fun lift(value: RustBuffer.ByValue): String {
        try {
            val byteArr = ByteArray(value.len.toInt())
            value.asByteBuffer()!!.get(byteArr)
            return byteArr.toString(Charsets.UTF_8)
        } finally {
            RustBuffer.free(value)
        }
    }

    override fun read(buf: ByteBuffer): String {
        val len = buf.getInt()
        val byteArr = ByteArray(len)
        buf.get(byteArr)
        return byteArr.toString(Charsets.UTF_8)
    }

    fun toUtf8(value: String): ByteBuffer {
        // Make sure we don't have invalid UTF-16, check for lone surrogates.
        return Charsets.UTF_8.newEncoder().run {
            onMalformedInput(CodingErrorAction.REPORT)
            encode(CharBuffer.wrap(value))
        }
    }

    override fun lower(value: String): RustBuffer.ByValue {
        val byteBuf = toUtf8(value)
        // Ideally we'd pass these bytes to `ffi_bytebuffer_from_bytes`, but doing so would require us
        // to copy them into a JNA `Memory`. So we might as well directly copy them into a `RustBuffer`.
        val rbuf = RustBuffer.alloc(byteBuf.limit().toULong())
        rbuf.asByteBuffer()!!.put(byteBuf)
        return rbuf
    }

    // We aren't sure exactly how many bytes our string will be once it's UTF-8
    // encoded.  Allocate 3 bytes per UTF-16 code unit which will always be
    // enough.
    override fun allocationSize(value: String): ULong {
        val sizeForLength = 4UL
        val sizeForString = value.length.toULong() * 3UL
        return sizeForLength + sizeForString
    }

    override fun write(value: String, buf: ByteBuffer) {
        val byteBuf = toUtf8(value)
        buf.putInt(byteBuf.limit())
        buf.put(byteBuf)
    }
}

/**
 * @suppress
 */
public object FfiConverterByteArray: FfiConverterRustBuffer<ByteArray> {
    override fun read(buf: ByteBuffer): ByteArray {
        val len = buf.getInt()
        val byteArr = ByteArray(len)
        buf.get(byteArr)
        return byteArr
    }
    override fun allocationSize(value: ByteArray): ULong {
        return 4UL + value.size.toULong()
    }
    override fun write(value: ByteArray, buf: ByteBuffer) {
        buf.putInt(value.size)
        buf.put(value)
    }
}


// This template implements a class for working with a Rust struct via a handle
// to the live Rust struct on the other side of the FFI.
//
// There's some subtlety here, because we have to be careful not to operate on a Rust
// struct after it has been dropped, and because we must expose a public API for freeing
// theq Kotlin wrapper object in lieu of reliable finalizers. The core requirements are:
//
//   * Each instance holds an opaque handle to the underlying Rust struct.
//     Method calls need to read this handle from the object's state and pass it in to
//     the Rust FFI.
//
//   * When an instance is no longer needed, its handle should be passed to a
//     special destructor function provided by the Rust FFI, which will drop the
//     underlying Rust struct.
//
//   * Given an instance, calling code is expected to call the special
//     `destroy` method in order to free it after use, either by calling it explicitly
//     or by using a higher-level helper like the `use` method. Failing to do so risks
//     leaking the underlying Rust struct.
//
//   * We can't assume that calling code will do the right thing, and must be prepared
//     to handle Kotlin method calls executing concurrently with or even after a call to
//     `destroy`, and to handle multiple (possibly concurrent!) calls to `destroy`.
//
//   * We must never allow Rust code to operate on the underlying Rust struct after
//     the destructor has been called, and must never call the destructor more than once.
//     Doing so may trigger memory unsafety.
//
//   * To mitigate many of the risks of leaking memory and use-after-free unsafety, a `Cleaner`
//     is implemented to call the destructor when the Kotlin object becomes unreachable.
//     This is done in a background thread. This is not a panacea, and client code should be aware that
//      1. the thread may starve if some there are objects that have poorly performing
//     `drop` methods or do significant work in their `drop` methods.
//      2. the thread is shared across the whole library. This can be tuned by using `android_cleaner = true`,
//         or `android = true` in the [`kotlin` section of the `uniffi.toml` file](https://mozilla.github.io/uniffi-rs/kotlin/configuration.html).
//
// If we try to implement this with mutual exclusion on access to the handle, there is the
// possibility of a race between a method call and a concurrent call to `destroy`:
//
//    * Thread A starts a method call, reads the value of the handle, but is interrupted
//      before it can pass the handle over the FFI to Rust.
//    * Thread B calls `destroy` and frees the underlying Rust struct.
//    * Thread A resumes, passing the already-read handle value to Rust and triggering
//      a use-after-free.
//
// One possible solution would be to use a `ReadWriteLock`, with each method call taking
// a read lock (and thus allowed to run concurrently) and the special `destroy` method
// taking a write lock (and thus blocking on live method calls). However, we aim not to
// generate methods with any hidden blocking semantics, and a `destroy` method that might
// block if called incorrectly seems to meet that bar.
//
// So, we achieve our goals by giving each instance an associated `AtomicLong` counter to track
// the number of in-flight method calls, and an `AtomicBoolean` flag to indicate whether `destroy`
// has been called. These are updated according to the following rules:
//
//    * The initial value of the counter is 1, indicating a live object with no in-flight calls.
//      The initial value for the flag is false.
//
//    * At the start of each method call, we atomically check the counter.
//      If it is 0 then the underlying Rust struct has already been destroyed and the call is aborted.
//      If it is nonzero them we atomically increment it by 1 and proceed with the method call.
//
//    * At the end of each method call, we atomically decrement and check the counter.
//      If it has reached zero then we destroy the underlying Rust struct.
//
//    * When `destroy` is called, we atomically flip the flag from false to true.
//      If the flag was already true we silently fail.
//      Otherwise we atomically decrement and check the counter.
//      If it has reached zero then we destroy the underlying Rust struct.
//
// Astute readers may observe that this all sounds very similar to the way that Rust's `Arc<T>` works,
// and indeed it is, with the addition of a flag to guard against multiple calls to `destroy`.
//
// The overall effect is that the underlying Rust struct is destroyed only when `destroy` has been
// called *and* all in-flight method calls have completed, avoiding violating any of the expectations
// of the underlying Rust code.
//
// This makes a cleaner a better alternative to _not_ calling `destroy()` as
// and when the object is finished with, but the abstraction is not perfect: if the Rust object's `drop`
// method is slow, and/or there are many objects to cleanup, and it's on a low end Android device, then the cleaner
// thread may be starved, and the app will leak memory.
//
// In this case, `destroy`ing manually may be a better solution.
//
// The cleaner can live side by side with the manual calling of `destroy`. In the order of responsiveness, uniffi objects
// with Rust peers are reclaimed:
//
// 1. By calling the `destroy` method of the object, which calls `rustObject.free()`. If that doesn't happen:
// 2. When the object becomes unreachable, AND the Cleaner thread gets to call `rustObject.free()`. If the thread is starved then:
// 3. The memory is reclaimed when the process terminates.
//
// [1] https://stackoverflow.com/questions/24376768/can-java-finalize-an-object-when-it-is-still-in-scope/24380219
//


/**
 * Opaque handle returned by `start`. Holds the runtime, the shutdown
 * signal, the IPC socket path, and a continuously-updated snapshot of
 * the daemon's last state JSON. Drop = no-op (Kotlin must call `stop`
 * explicitly so the daemon thread joins deterministically).
 */
public interface FluxsyncHandleInterface {
    
    /**
     * Fetch a clipboard item's raw bytes by its hex content hash. Used by
     * the Android client to pull an inbound image's PNG on demand — the
     * state JSON only carries the hash + a label, never the bytes.
     */
    fun `fetchItem`(`hash`: kotlin.String): kotlin.ByteArray
    
    /**
     * Highest log seq observed so far. Useful for Kotlin's first poll
     * when it wants only new entries (subscribe-after-attach pattern).
     */
    fun `logCursor`(): kotlin.ULong
    
    /**
     * Manual pair fallback. Pass `addr = ""` to skip the immediate
     * handshake (mDNS will pick the peer up later); pass `IP:PORT` to
     * kick the handshake right away.
     */
    fun `pairAccept`(`pubkeyB32`: kotlin.String, `name`: kotlin.String, `addr`: kotlin.String)
    
    /**
     * FS-052: accept or reject a pending pair after the user has compared the
     * 6 SAS words on both devices. `accept = true` clears the gate so
     * clipboard can flow; `accept = false` revokes the peer entirely.
     */
    fun `pairConfirm`(`peerId`: kotlin.String, `accept`: kotlin.Boolean)
    
    /**
     * Trust a peer described by a `fluxsync://pair/...` URI (typically
     * from a scanned QR). `name` is the nickname for the peer.
     */
    fun `pairFromUri`(`uri`: kotlin.String, `name`: kotlin.String)
    
    /**
     * FS-052: list TOFU pairs awaiting verbal SAS confirmation. Returns the
     * raw `data` JSON array (`[{peer_id, name, sas_words, ...}]`) so the UI
     * can render the 6-word compare after a scan. Empty array once the user
     * has confirmed (or if nothing is pending).
     */
    fun `pairPending`(): kotlin.String
    
    /**
     * This device's pair info as JSON (matches `CmdData::PairInfo`).
     */
    fun `pairShow`(): kotlin.String
    
    /**
     * Returns log entries with `seq > since`. Pass `0` to fetch the
     * whole buffer at startup; pass the highest seq seen so far on
     * subsequent polls so the Kotlin side only walks new entries.
     */
    fun `pollLogs`(`since`: kotlin.ULong): List<FfiLogEntry>
    
    /**
     * Latest state JSON, or `""` before the daemon has published its
     * first snapshot. Pollable from any Kotlin coroutine — the read is
     * O(1) and lock-cheap.
     */
    fun `pollState`(): kotlin.String
    
    /**
     * Inject a typed clipboard item. `kind` is `"text"` or `"image"`;
     * `bytes` is the raw payload (UTF-8 for text, PNG for image). Image
     * bytes ride to the daemon as base64 since the IPC channel is NDJSON.
     */
    fun `pushItem`(`kind`: kotlin.String, `bytes`: kotlin.ByteArray)
    
    /**
     * Inject a clipboard item. Same code path as `fluxctl push`.
     */
    fun `pushText`(`text`: kotlin.String)
    
    /**
     * FluxFirewall: approve (`allow = true`) or reject an item parked under an
     * Ask rule, keyed by its hex content hash from `State.pending`. Approval
     * sends/writes the held item; rejection drops it silently.
     */
    fun `resolvePending`(`hash`: kotlin.String, `allow`: kotlin.Boolean)
    
    /**
     * FluxMesh: revoke one specific peer by hex peer-id (drops its
     * session + removes it from the trust store), leaving every other
     * paired device linked. Drives the per-secondary "Unpair" button in
     * the mesh peer list. `unpair` (above) tears down only the active
     * primary; this is the surgical single-peer version.
     */
    fun `revoke`(`peerId`: kotlin.String)
    
    /**
     * Pause-below-X% battery threshold (5..=50).
     */
    fun `setBatteryThreshold`(`value`: kotlin.UByte)
    
    /**
     * "Resume while charging" override.
     */
    fun `setChargeOverride`(`value`: kotlin.Boolean)
    
    /**
     * FluxVault: pin (`favorite = true`) or unpin a history item by its hex
     * content hash. Pinned items survive the vault's TTL + disk cap.
     */
    fun `setFavorite`(`hash`: kotlin.String, `favorite`: kotlin.Boolean)
    
    /**
     * FluxFirewall: replace the whole clipboard firewall policy. `policy_json`
     * is the serialized `FirewallPolicy` object (`enabled` + the per-kind
     * rules); the daemon swaps it in and re-emits state so the Android
     * toggles reflect the new rules immediately. Parsing here keeps a
     * malformed object from reaching the daemon as an opaque IPC error.
     */
    fun `setFirewall`(`policyJson`: kotlin.String)
    
    /**
     * Push host-OS battery telemetry into the daemon. Called from the
     * Android `MainActivity` whenever the system fires
     * `ACTION_BATTERY_CHANGED`. Without this, the daemon reports a
     * hardcoded value to the peer.
     */
    fun `setSelfBattery`(`level`: kotlin.UByte, `charging`: kotlin.Boolean)
    
    /**
     * Fire the shutdown notify and join the daemon thread. Returns
     * once the daemon has exited (≤ 500ms in practice).
     */
    fun `stop`()
    
    /**
     * Wake / sleep the FSM. `true` = `Idle → Discovering`.
     */
    fun `toggle`(`on`: kotlin.Boolean)
    
    /**
     * Manually unpair from the current peer and reset the FSM state.
     * The Android UI calls this when the user taps "Unpair" on the
     * Reconnecting screen, or when the system detects a stale ghost.
     */
    fun `unpair`()
    
    companion object
}

/**
 * Opaque handle returned by `start`. Holds the runtime, the shutdown
 * signal, the IPC socket path, and a continuously-updated snapshot of
 * the daemon's last state JSON. Drop = no-op (Kotlin must call `stop`
 * explicitly so the daemon thread joins deterministically).
 */
open class FluxsyncHandle: Disposable, AutoCloseable, FluxsyncHandleInterface
{

    @Suppress("UNUSED_PARAMETER")
    /**
     * @suppress
     */
    constructor(withHandle: UniffiWithHandle, handle: Long) {
        this.handle = handle
        this.cleanable = UniffiLib.CLEANER.register(this, UniffiCleanAction(handle))
    }

    /**
     * @suppress
     *
     * This constructor can be used to instantiate a fake object. Only used for tests. Any
     * attempt to actually use an object constructed this way will fail as there is no
     * connected Rust object.
     */
    @Suppress("UNUSED_PARAMETER")
    constructor(noHandle: NoHandle) {
        this.handle = 0
        this.cleanable = null
    }

    protected val handle: Long
    protected val cleanable: UniffiCleaner.Cleanable?

    private val wasDestroyed = AtomicBoolean(false)
    private val callCounter = AtomicLong(1)

    override fun destroy() {
        // Only allow a single call to this method.
        // TODO: maybe we should log a warning if called more than once?
        if (this.wasDestroyed.compareAndSet(false, true)) {
            // This decrement always matches the initial count of 1 given at creation time.
            if (this.callCounter.decrementAndGet() == 0L) {
                cleanable?.clean()
            }
        }
    }

    @Synchronized
    override fun close() {
        this.destroy()
    }

    internal inline fun <R> callWithHandle(block: (handle: Long) -> R): R {
        // Check and increment the call counter, to keep the object alive.
        // This needs a compare-and-set retry loop in case of concurrent updates.
        do {
            val c = this.callCounter.get()
            if (c == 0L) {
                throw IllegalStateException("${this.javaClass.simpleName} object has already been destroyed")
            }
            if (c == Long.MAX_VALUE) {
                throw IllegalStateException("${this.javaClass.simpleName} call counter would overflow")
            }
        } while (! this.callCounter.compareAndSet(c, c + 1L))
        // Now we can safely do the method call without the handle being freed concurrently.
        try {
            return block(this.uniffiCloneHandle())
        } finally {
            // This decrement always matches the increment we performed above.
            if (this.callCounter.decrementAndGet() == 0L) {
                cleanable?.clean()
            }
        }
    }

    // Use a static inner class instead of a closure so as not to accidentally
    // capture `this` as part of the cleanable's action.
    private class UniffiCleanAction(private val handle: Long) : Runnable {
        override fun run() {
            if (handle == 0.toLong()) {
                // Fake object created with `NoHandle`, don't try to free.
                return;
            }
            uniffiRustCall { status ->
                UniffiLib.uniffi_fluxsync_mobile_ffi_fn_free_fluxsynchandle(handle, status)
            }
        }
    }

    /**
     * @suppress
     */
    fun uniffiCloneHandle(): Long {
        if (handle == 0.toLong()) {
            throw InternalException("uniffiCloneHandle() called on NoHandle object");
        }
        return uniffiRustCall() { status ->
            UniffiLib.uniffi_fluxsync_mobile_ffi_fn_clone_fluxsynchandle(handle, status)
        }
    }

    
    /**
     * Fetch a clipboard item's raw bytes by its hex content hash. Used by
     * the Android client to pull an inbound image's PNG on demand — the
     * state JSON only carries the hash + a label, never the bytes.
     */
    @Throws(FluxException::class)override fun `fetchItem`(`hash`: kotlin.String): kotlin.ByteArray {
            return FfiConverterByteArray.lift(
    callWithHandle {
    uniffiRustCallWithError(FluxException) { _status ->
    UniffiLib.uniffi_fluxsync_mobile_ffi_fn_method_fluxsynchandle_fetch_item(
        it,
        FfiConverterString.lower(`hash`),_status)
}
    }
    )
    }
    

    
    /**
     * Highest log seq observed so far. Useful for Kotlin's first poll
     * when it wants only new entries (subscribe-after-attach pattern).
     */override fun `logCursor`(): kotlin.ULong {
            return FfiConverterULong.lift(
    callWithHandle {
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_fluxsync_mobile_ffi_fn_method_fluxsynchandle_log_cursor(
        it,
        _status)
}
    }
    )
    }
    

    
    /**
     * Manual pair fallback. Pass `addr = ""` to skip the immediate
     * handshake (mDNS will pick the peer up later); pass `IP:PORT` to
     * kick the handshake right away.
     */
    @Throws(FluxException::class)override fun `pairAccept`(`pubkeyB32`: kotlin.String, `name`: kotlin.String, `addr`: kotlin.String)
        = 
    callWithHandle {
    uniffiRustCallWithError(FluxException) { _status ->
    UniffiLib.uniffi_fluxsync_mobile_ffi_fn_method_fluxsynchandle_pair_accept(
        it,
        FfiConverterString.lower(`pubkeyB32`),FfiConverterString.lower(`name`),FfiConverterString.lower(`addr`),_status)
}
    }
    
    

    
    /**
     * FS-052: accept or reject a pending pair after the user has compared the
     * 6 SAS words on both devices. `accept = true` clears the gate so
     * clipboard can flow; `accept = false` revokes the peer entirely.
     */
    @Throws(FluxException::class)override fun `pairConfirm`(`peerId`: kotlin.String, `accept`: kotlin.Boolean)
        = 
    callWithHandle {
    uniffiRustCallWithError(FluxException) { _status ->
    UniffiLib.uniffi_fluxsync_mobile_ffi_fn_method_fluxsynchandle_pair_confirm(
        it,
        FfiConverterString.lower(`peerId`),FfiConverterBoolean.lower(`accept`),_status)
}
    }
    
    

    
    /**
     * Trust a peer described by a `fluxsync://pair/...` URI (typically
     * from a scanned QR). `name` is the nickname for the peer.
     */
    @Throws(FluxException::class)override fun `pairFromUri`(`uri`: kotlin.String, `name`: kotlin.String)
        = 
    callWithHandle {
    uniffiRustCallWithError(FluxException) { _status ->
    UniffiLib.uniffi_fluxsync_mobile_ffi_fn_method_fluxsynchandle_pair_from_uri(
        it,
        FfiConverterString.lower(`uri`),FfiConverterString.lower(`name`),_status)
}
    }
    
    

    
    /**
     * FS-052: list TOFU pairs awaiting verbal SAS confirmation. Returns the
     * raw `data` JSON array (`[{peer_id, name, sas_words, ...}]`) so the UI
     * can render the 6-word compare after a scan. Empty array once the user
     * has confirmed (or if nothing is pending).
     */
    @Throws(FluxException::class)override fun `pairPending`(): kotlin.String {
            return FfiConverterString.lift(
    callWithHandle {
    uniffiRustCallWithError(FluxException) { _status ->
    UniffiLib.uniffi_fluxsync_mobile_ffi_fn_method_fluxsynchandle_pair_pending(
        it,
        _status)
}
    }
    )
    }
    

    
    /**
     * This device's pair info as JSON (matches `CmdData::PairInfo`).
     */
    @Throws(FluxException::class)override fun `pairShow`(): kotlin.String {
            return FfiConverterString.lift(
    callWithHandle {
    uniffiRustCallWithError(FluxException) { _status ->
    UniffiLib.uniffi_fluxsync_mobile_ffi_fn_method_fluxsynchandle_pair_show(
        it,
        _status)
}
    }
    )
    }
    

    
    /**
     * Returns log entries with `seq > since`. Pass `0` to fetch the
     * whole buffer at startup; pass the highest seq seen so far on
     * subsequent polls so the Kotlin side only walks new entries.
     */override fun `pollLogs`(`since`: kotlin.ULong): List<FfiLogEntry> {
            return FfiConverterSequenceTypeFfiLogEntry.lift(
    callWithHandle {
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_fluxsync_mobile_ffi_fn_method_fluxsynchandle_poll_logs(
        it,
        FfiConverterULong.lower(`since`),_status)
}
    }
    )
    }
    

    
    /**
     * Latest state JSON, or `""` before the daemon has published its
     * first snapshot. Pollable from any Kotlin coroutine — the read is
     * O(1) and lock-cheap.
     */override fun `pollState`(): kotlin.String {
            return FfiConverterString.lift(
    callWithHandle {
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_fluxsync_mobile_ffi_fn_method_fluxsynchandle_poll_state(
        it,
        _status)
}
    }
    )
    }
    

    
    /**
     * Inject a typed clipboard item. `kind` is `"text"` or `"image"`;
     * `bytes` is the raw payload (UTF-8 for text, PNG for image). Image
     * bytes ride to the daemon as base64 since the IPC channel is NDJSON.
     */
    @Throws(FluxException::class)override fun `pushItem`(`kind`: kotlin.String, `bytes`: kotlin.ByteArray)
        = 
    callWithHandle {
    uniffiRustCallWithError(FluxException) { _status ->
    UniffiLib.uniffi_fluxsync_mobile_ffi_fn_method_fluxsynchandle_push_item(
        it,
        FfiConverterString.lower(`kind`),FfiConverterByteArray.lower(`bytes`),_status)
}
    }
    
    

    
    /**
     * Inject a clipboard item. Same code path as `fluxctl push`.
     */
    @Throws(FluxException::class)override fun `pushText`(`text`: kotlin.String)
        = 
    callWithHandle {
    uniffiRustCallWithError(FluxException) { _status ->
    UniffiLib.uniffi_fluxsync_mobile_ffi_fn_method_fluxsynchandle_push_text(
        it,
        FfiConverterString.lower(`text`),_status)
}
    }
    
    

    
    /**
     * FluxFirewall: approve (`allow = true`) or reject an item parked under an
     * Ask rule, keyed by its hex content hash from `State.pending`. Approval
     * sends/writes the held item; rejection drops it silently.
     */
    @Throws(FluxException::class)override fun `resolvePending`(`hash`: kotlin.String, `allow`: kotlin.Boolean)
        = 
    callWithHandle {
    uniffiRustCallWithError(FluxException) { _status ->
    UniffiLib.uniffi_fluxsync_mobile_ffi_fn_method_fluxsynchandle_resolve_pending(
        it,
        FfiConverterString.lower(`hash`),FfiConverterBoolean.lower(`allow`),_status)
}
    }
    
    

    
    /**
     * FluxMesh: revoke one specific peer by hex peer-id (drops its
     * session + removes it from the trust store), leaving every other
     * paired device linked. Drives the per-secondary "Unpair" button in
     * the mesh peer list. `unpair` (above) tears down only the active
     * primary; this is the surgical single-peer version.
     */
    @Throws(FluxException::class)override fun `revoke`(`peerId`: kotlin.String)
        = 
    callWithHandle {
    uniffiRustCallWithError(FluxException) { _status ->
    UniffiLib.uniffi_fluxsync_mobile_ffi_fn_method_fluxsynchandle_revoke(
        it,
        FfiConverterString.lower(`peerId`),_status)
}
    }
    
    

    
    /**
     * Pause-below-X% battery threshold (5..=50).
     */
    @Throws(FluxException::class)override fun `setBatteryThreshold`(`value`: kotlin.UByte)
        = 
    callWithHandle {
    uniffiRustCallWithError(FluxException) { _status ->
    UniffiLib.uniffi_fluxsync_mobile_ffi_fn_method_fluxsynchandle_set_battery_threshold(
        it,
        FfiConverterUByte.lower(`value`),_status)
}
    }
    
    

    
    /**
     * "Resume while charging" override.
     */
    @Throws(FluxException::class)override fun `setChargeOverride`(`value`: kotlin.Boolean)
        = 
    callWithHandle {
    uniffiRustCallWithError(FluxException) { _status ->
    UniffiLib.uniffi_fluxsync_mobile_ffi_fn_method_fluxsynchandle_set_charge_override(
        it,
        FfiConverterBoolean.lower(`value`),_status)
}
    }
    
    

    
    /**
     * FluxVault: pin (`favorite = true`) or unpin a history item by its hex
     * content hash. Pinned items survive the vault's TTL + disk cap.
     */
    @Throws(FluxException::class)override fun `setFavorite`(`hash`: kotlin.String, `favorite`: kotlin.Boolean)
        = 
    callWithHandle {
    uniffiRustCallWithError(FluxException) { _status ->
    UniffiLib.uniffi_fluxsync_mobile_ffi_fn_method_fluxsynchandle_set_favorite(
        it,
        FfiConverterString.lower(`hash`),FfiConverterBoolean.lower(`favorite`),_status)
}
    }
    
    

    
    /**
     * FluxFirewall: replace the whole clipboard firewall policy. `policy_json`
     * is the serialized `FirewallPolicy` object (`enabled` + the per-kind
     * rules); the daemon swaps it in and re-emits state so the Android
     * toggles reflect the new rules immediately. Parsing here keeps a
     * malformed object from reaching the daemon as an opaque IPC error.
     */
    @Throws(FluxException::class)override fun `setFirewall`(`policyJson`: kotlin.String)
        = 
    callWithHandle {
    uniffiRustCallWithError(FluxException) { _status ->
    UniffiLib.uniffi_fluxsync_mobile_ffi_fn_method_fluxsynchandle_set_firewall(
        it,
        FfiConverterString.lower(`policyJson`),_status)
}
    }
    
    

    
    /**
     * Push host-OS battery telemetry into the daemon. Called from the
     * Android `MainActivity` whenever the system fires
     * `ACTION_BATTERY_CHANGED`. Without this, the daemon reports a
     * hardcoded value to the peer.
     */
    @Throws(FluxException::class)override fun `setSelfBattery`(`level`: kotlin.UByte, `charging`: kotlin.Boolean)
        = 
    callWithHandle {
    uniffiRustCallWithError(FluxException) { _status ->
    UniffiLib.uniffi_fluxsync_mobile_ffi_fn_method_fluxsynchandle_set_self_battery(
        it,
        FfiConverterUByte.lower(`level`),FfiConverterBoolean.lower(`charging`),_status)
}
    }
    
    

    
    /**
     * Fire the shutdown notify and join the daemon thread. Returns
     * once the daemon has exited (≤ 500ms in practice).
     */override fun `stop`()
        = 
    callWithHandle {
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_fluxsync_mobile_ffi_fn_method_fluxsynchandle_stop(
        it,
        _status)
}
    }
    
    

    
    /**
     * Wake / sleep the FSM. `true` = `Idle → Discovering`.
     */
    @Throws(FluxException::class)override fun `toggle`(`on`: kotlin.Boolean)
        = 
    callWithHandle {
    uniffiRustCallWithError(FluxException) { _status ->
    UniffiLib.uniffi_fluxsync_mobile_ffi_fn_method_fluxsynchandle_toggle(
        it,
        FfiConverterBoolean.lower(`on`),_status)
}
    }
    
    

    
    /**
     * Manually unpair from the current peer and reset the FSM state.
     * The Android UI calls this when the user taps "Unpair" on the
     * Reconnecting screen, or when the system detects a stale ghost.
     */
    @Throws(FluxException::class)override fun `unpair`()
        = 
    callWithHandle {
    uniffiRustCallWithError(FluxException) { _status ->
    UniffiLib.uniffi_fluxsync_mobile_ffi_fn_method_fluxsynchandle_unpair(
        it,
        _status)
}
    }
    
    

    

    


    
    companion object {
        
    /**
     * Boot the daemon. Returns once the IPC socket is reachable and a
     * state-subscriber task is running. Pass `IdentitySource::Keystore`
     * for the normal "remember pairing across reboots" path.
     */
    @Throws(FluxException::class) fun `start`(`peerName`: kotlin.String, `ipcPath`: kotlin.String, `udpPort`: kotlin.UShort, `identity`: IdentitySource): FluxsyncHandle {
            return FfiConverterTypeFluxsyncHandle.lift(
    uniffiRustCallWithError(FluxException) { _status ->
    UniffiLib.uniffi_fluxsync_mobile_ffi_fn_constructor_fluxsynchandle_start(
    
        FfiConverterString.lower(`peerName`),FfiConverterString.lower(`ipcPath`),FfiConverterUShort.lower(`udpPort`),FfiConverterTypeIdentitySource.lower(`identity`),_status)
}
    )
    }
    

        
    }
    
}


/**
 * @suppress
 */
public object FfiConverterTypeFluxsyncHandle: FfiConverter<FluxsyncHandle, Long> {
    override fun lower(value: FluxsyncHandle): Long {
        return value.uniffiCloneHandle()
    }

    override fun lift(value: Long): FluxsyncHandle {
        return FluxsyncHandle(UniffiWithHandle, value)
    }

    override fun read(buf: ByteBuffer): FluxsyncHandle {
        return lift(buf.getLong())
    }

    override fun allocationSize(value: FluxsyncHandle) = 8UL

    override fun write(value: FluxsyncHandle, buf: ByteBuffer) {
        buf.putLong(lower(value))
    }
}



/**
 * One row of the Logs screen — synthesized at FFI receipt from the
 * daemon's `LogEntry` plus a monotonic `seq` cursor so the Kotlin side
 * can ask for "everything since seq N" without re-sending the whole
 * buffer. `time` is UTC HH:MM:SS, formatted client-side; `raw` is the
 * untouched JSON line for the LogsScreen "RAW" toggle.
 */
data class FfiLogEntry (
    val `seq`: kotlin.ULong
    , 
    val `time`: kotlin.String
    , 
    val `level`: kotlin.String
    , 
    val `msg`: kotlin.String
    , 
    val `raw`: kotlin.String
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeFfiLogEntry: FfiConverterRustBuffer<FfiLogEntry> {
    override fun read(buf: ByteBuffer): FfiLogEntry {
        return FfiLogEntry(
            FfiConverterULong.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: FfiLogEntry) = (
            FfiConverterULong.allocationSize(value.`seq`) +
            FfiConverterString.allocationSize(value.`time`) +
            FfiConverterString.allocationSize(value.`level`) +
            FfiConverterString.allocationSize(value.`msg`) +
            FfiConverterString.allocationSize(value.`raw`)
    )

    override fun write(value: FfiLogEntry, buf: ByteBuffer) {
            FfiConverterULong.write(value.`seq`, buf)
            FfiConverterString.write(value.`time`, buf)
            FfiConverterString.write(value.`level`, buf)
            FfiConverterString.write(value.`msg`, buf)
            FfiConverterString.write(value.`raw`, buf)
    }
}





/**
 * All FFI errors funnel here. `flat_error` flattens the variants into
 * a single Kotlin `FluxException` class — UniFFI 0.27's per-variant
 * codegen is buggy when variants carry field data. Kotlin still gets
 * the message via `Throwable::getLocalizedMessage`.
 */
sealed class FluxException(message: String): kotlin.Exception(message) {
        
        class Identity(message: String) : FluxException(message)
        
        class Daemon(message: String) : FluxException(message)
        
        class Ipc(message: String) : FluxException(message)
        
        class Invalid(message: String) : FluxException(message)
        

    companion object ErrorHandler : UniffiRustCallStatusErrorHandler<FluxException> {
        override fun lift(error_buf: RustBuffer.ByValue): FluxException = FfiConverterTypeFluxError.lift(error_buf)
    }
}

/**
 * @suppress
 */
public object FfiConverterTypeFluxError : FfiConverterRustBuffer<FluxException> {
    override fun read(buf: ByteBuffer): FluxException {
        
            return when(buf.getInt()) {
            1 -> FluxException.Identity(FfiConverterString.read(buf))
            2 -> FluxException.Daemon(FfiConverterString.read(buf))
            3 -> FluxException.Ipc(FfiConverterString.read(buf))
            4 -> FluxException.Invalid(FfiConverterString.read(buf))
            else -> throw RuntimeException("invalid error enum value, something is very wrong!!")
        }
        
    }

    override fun allocationSize(value: FluxException): ULong {
        return 4UL
    }

    override fun write(value: FluxException, buf: ByteBuffer) {
        when(value) {
            is FluxException.Identity -> {
                buf.putInt(1)
                Unit
            }
            is FluxException.Daemon -> {
                buf.putInt(2)
                Unit
            }
            is FluxException.Ipc -> {
                buf.putInt(3)
                Unit
            }
            is FluxException.Invalid -> {
                buf.putInt(4)
                Unit
            }
        }.let { /* this makes the `when` an expression, which ensures it is exhaustive */ }
    }

}



/**
 * SE-05: source of the long-term identity, replacing the older trio of
 * `keystore_dir` / `identity_secret_b64` empty-string sentinels.
 * The empty-string overloads silently destroyed pairings when a caller
 * passed `""` by mistake — a typed enum makes that misuse impossible.
 */
sealed class IdentitySource {
    
    /**
     * Generate a fresh keypair on every start.
     * **Destroys any existing pairing** — pick this only for first-run
     * or "reset device" flows.
     */
    object Generate : IdentitySource()
    
    
    /**
     * Load the persisted identity from `dir`, or create+persist a new
     * one if none exists. This is the normal mobile path.
     */
    data class Keystore(
        val `dir`: kotlin.String) : IdentitySource()
        
    {
        

        companion object
    }
    
    /**
     * Decode a base64-encoded 32-byte secret. Testing / migration only —
     * production callers should use `Keystore`.
     */
    data class SecretBase64(
        val `secret`: kotlin.String) : IdentitySource()
        
    {
        

        companion object
    }
    

    

    
    


    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeIdentitySource : FfiConverterRustBuffer<IdentitySource>{
    override fun read(buf: ByteBuffer): IdentitySource {
        return when(buf.getInt()) {
            1 -> IdentitySource.Generate
            2 -> IdentitySource.Keystore(
                FfiConverterString.read(buf),
                )
            3 -> IdentitySource.SecretBase64(
                FfiConverterString.read(buf),
                )
            else -> throw RuntimeException("invalid enum value, something is very wrong!!")
        }
    }

    override fun allocationSize(value: IdentitySource) = when(value) {
        is IdentitySource.Generate -> {
            // Add the size for the Int that specifies the variant plus the size needed for all fields
            (
                4UL
            )
        }
        is IdentitySource.Keystore -> {
            // Add the size for the Int that specifies the variant plus the size needed for all fields
            (
                4UL
                + FfiConverterString.allocationSize(value.`dir`)
            )
        }
        is IdentitySource.SecretBase64 -> {
            // Add the size for the Int that specifies the variant plus the size needed for all fields
            (
                4UL
                + FfiConverterString.allocationSize(value.`secret`)
            )
        }
    }

    override fun write(value: IdentitySource, buf: ByteBuffer) {
        when(value) {
            is IdentitySource.Generate -> {
                buf.putInt(1)
                Unit
            }
            is IdentitySource.Keystore -> {
                buf.putInt(2)
                FfiConverterString.write(value.`dir`, buf)
                Unit
            }
            is IdentitySource.SecretBase64 -> {
                buf.putInt(3)
                FfiConverterString.write(value.`secret`, buf)
                Unit
            }
        }.let { /* this makes the `when` an expression, which ensures it is exhaustive */ }
    }
}






/**
 * @suppress
 */
public object FfiConverterSequenceTypeFfiLogEntry: FfiConverterRustBuffer<List<FfiLogEntry>> {
    override fun read(buf: ByteBuffer): List<FfiLogEntry> {
        val len = buf.getInt()
        return List<FfiLogEntry>(len) {
            FfiConverterTypeFfiLogEntry.read(buf)
        }
    }

    override fun allocationSize(value: List<FfiLogEntry>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeFfiLogEntry.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<FfiLogEntry>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeFfiLogEntry.write(it, buf)
        }
    }
}

